title: Nimisha Sen
#logo: /assets/img/...
description: I’m a data professional with a background in law, design, and creative technology. Recently, completed my MSc Data Science & AI. My work bridges structured thinking, storytelling, and intelligent systems. Whether I’m building data pipelines, designing interactive experiences, or writing about the intersection of ethics and AI — I aim to make complex things feel thoughtful and clear.
show_downloads: true
theme: jekyll-theme-minimal
